updates

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -5,19 +5,19 @@ iatest=$(expr index "$-" i)
 # SOURCED ALIAS'S AND SCRIPTS BY zachbrowne.me
 #######################################################
 if [ -f /usr/bin/fastfetch ]; then
-	fastfetch
+  fastfetch
 fi
 
 # Source global definitions
 if [ -f /etc/bashrc ]; then
-	. /etc/bashrc
+  . /etc/bashrc
 fi
 
 # Enable bash programmable completion features in interactive shells
 if [ -f /usr/share/bash-completion/bash_completion ]; then
-	. /usr/share/bash-completion/bash_completion
+  . /usr/share/bash-completion/bash_completion
 elif [ -f /etc/bash_completion ]; then
-	. /etc/bash_completion
+  . /etc/bash_completion
 fi
 
 #######################################################
@@ -76,12 +76,12 @@ export LS_COLORS='no=00:fi=00:di=00;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40
 #export GREP_OPTIONS='--color=auto' #deprecated
 
 # Check if ripgrep is installed
-if command -v rg &> /dev/null; then
-    # Alias grep to rg if ripgrep is installed
-    alias grep='rg'
+if command -v rg &>/dev/null; then
+  # Alias grep to rg if ripgrep is installed
+  alias grep='rg'
 else
-    # Alias grep to /usr/bin/grep with GREP_OPTIONS if ripgrep is not installed
-    alias grep="/usr/bin/grep $GREP_OPTIONS"
+  # Alias grep to /usr/bin/grep with GREP_OPTIONS if ripgrep is not installed
+  alias grep="/usr/bin/grep $GREP_OPTIONS"
 fi
 unset GREP_OPTIONS
 
@@ -143,7 +143,6 @@ alias freshclam='sudo freshclam'
 alias vi='nvim'
 alias svi='sudo vi'
 alias vis='nvim "+set si"'
-
 
 # Change directory aliases
 alias home='cd ~'
@@ -237,50 +236,49 @@ alias clickpaste='sleep 3; xdotool type "$(xclip -o -selection clipboard)"'
 
 alias kssh="kitty +kitten ssh"
 
-
 #######################################################
 # SPECIAL FUNCTIONS
 #######################################################
 # Extracts any archive(s) (if unp isn't installed)
 extract() {
-	for archive in "$@"; do
-		if [ -f "$archive" ]; then
-			case $archive in
-			*.tar.bz2) tar xvjf $archive ;;
-			*.tar.gz) tar xvzf $archive ;;
-			*.bz2) bunzip2 $archive ;;
-			*.rar) rar x $archive ;;
-			*.gz) gunzip $archive ;;
-			*.tar) tar xvf $archive ;;
-			*.tbz2) tar xvjf $archive ;;
-			*.tgz) tar xvzf $archive ;;
-			*.zip) unzip $archive ;;
-			*.Z) uncompress $archive ;;
-			*.7z) 7z x $archive ;;
-			*) echo "don't know how to extract '$archive'..." ;;
-			esac
-		else
-			echo "'$archive' is not a valid file!"
-		fi
-	done
+  for archive in "$@"; do
+    if [ -f "$archive" ]; then
+      case $archive in
+      *.tar.bz2) tar xvjf $archive ;;
+      *.tar.gz) tar xvzf $archive ;;
+      *.bz2) bunzip2 $archive ;;
+      *.rar) rar x $archive ;;
+      *.gz) gunzip $archive ;;
+      *.tar) tar xvf $archive ;;
+      *.tbz2) tar xvjf $archive ;;
+      *.tgz) tar xvzf $archive ;;
+      *.zip) unzip $archive ;;
+      *.Z) uncompress $archive ;;
+      *.7z) 7z x $archive ;;
+      *) echo "don't know how to extract '$archive'..." ;;
+      esac
+    else
+      echo "'$archive' is not a valid file!"
+    fi
+  done
 }
 
 # Searches for text in all files in the current folder
 ftext() {
-	# -i case-insensitive
-	# -I ignore binary files
-	# -H causes filename to be printed
-	# -r recursive search
-	# -n causes line number to be printed
-	# optional: -F treat search term as a literal, not a regular expression
-	# optional: -l only print filenames and not the matching lines ex. grep -irl "$1" *
-	grep -iIHrn --color=always "$1" . | less -r
+  # -i case-insensitive
+  # -I ignore binary files
+  # -H causes filename to be printed
+  # -r recursive search
+  # -n causes line number to be printed
+  # optional: -F treat search term as a literal, not a regular expression
+  # optional: -l only print filenames and not the matching lines ex. grep -irl "$1" *
+  grep -iIHrn --color=always "$1" . | less -r
 }
 
 # Copy file with a progress bar
 cpp() {
-    set -e
-    strace -q -ewrite cp -- "${1}" "${2}" 2>&1 |
+  set -e
+  strace -q -ewrite cp -- "${1}" "${2}" 2>&1 |
     awk '{
         count += $NF
         if (count % 10 == 0) {
@@ -299,252 +297,250 @@ cpp() {
 
 # Copy and go to the directory
 cpg() {
-	if [ -d "$2" ]; then
-		cp "$1" "$2" && cd "$2"
-	else
-		cp "$1" "$2"
-	fi
+  if [ -d "$2" ]; then
+    cp "$1" "$2" && cd "$2"
+  else
+    cp "$1" "$2"
+  fi
 }
 
 # Move and go to the directory
 mvg() {
-	if [ -d "$2" ]; then
-		mv "$1" "$2" && cd "$2"
-	else
-		mv "$1" "$2"
-	fi
+  if [ -d "$2" ]; then
+    mv "$1" "$2" && cd "$2"
+  else
+    mv "$1" "$2"
+  fi
 }
 
 # Create and go to the directory
 mkdirg() {
-	mkdir -p "$1"
-	cd "$1"
+  mkdir -p "$1"
+  cd "$1"
 }
 
 # Goes up a specified number of directories  (i.e. up 4)
 up() {
-	local d=""
-	limit=$1
-	for ((i = 1; i <= limit; i++)); do
-		d=$d/..
-	done
-	d=$(echo $d | sed 's/^\///')
-	if [ -z "$d" ]; then
-		d=..
-	fi
-	cd $d
+  local d=""
+  limit=$1
+  for ((i = 1; i <= limit; i++)); do
+    d=$d/..
+  done
+  d=$(echo $d | sed 's/^\///')
+  if [ -z "$d" ]; then
+    d=..
+  fi
+  cd $d
 }
 
 # Automatically do an ls after each cd, z, or zoxide
-cd ()
-{
-	if [ -n "$1" ]; then
-		builtin cd "$@" && ls
-	else
-		builtin cd ~ && ls
-	fi
+cd() {
+  if [ -n "$1" ]; then
+    builtin cd "$@" && ls
+  else
+    builtin cd ~ && ls
+  fi
 }
 
 # Returns the last 2 fields of the working directory
 pwdtail() {
-	pwd | awk -F/ '{nlast = NF -1;print $nlast"/"$NF}'
+  pwd | awk -F/ '{nlast = NF -1;print $nlast"/"$NF}'
 }
 
 # Show the current distribution
-distribution () {
-    local dtype="unknown"  # Default to unknown
+distribution() {
+  local dtype="unknown" # Default to unknown
 
-    # Use /etc/os-release for modern distro identification
-    if [ -r /etc/os-release ]; then
-        source /etc/os-release
-        case $ID in
-            fedora|rhel|centos)
-                dtype="redhat"
-                ;;
-            sles|opensuse*)
-                dtype="suse"
-                ;;
-            ubuntu|debian)
-                dtype="debian"
-                ;;
-            gentoo)
-                dtype="gentoo"
-                ;;
-            arch|manjaro)
-                dtype="arch"
-                ;;
-            slackware)
-                dtype="slackware"
-                ;;
-            *)
-                # Check ID_LIKE only if dtype is still unknown
-                if [ -n "$ID_LIKE" ]; then
-                    case $ID_LIKE in
-                        *fedora*|*rhel*|*centos*)
-                            dtype="redhat"
-                            ;;
-                        *sles*|*opensuse*)
-                            dtype="suse"
-                            ;;
-                        *ubuntu*|*debian*)
-                            dtype="debian"
-                            ;;
-                        *gentoo*)
-                            dtype="gentoo"
-                            ;;
-                        *arch*)
-                            dtype="arch"
-                            ;;
-                        *slackware*)
-                            dtype="slackware"
-                            ;;
-                    esac
-                fi
-
-                # If ID or ID_LIKE is not recognized, keep dtype as unknown
-                ;;
+  # Use /etc/os-release for modern distro identification
+  if [ -r /etc/os-release ]; then
+    source /etc/os-release
+    case $ID in
+    fedora | rhel | centos)
+      dtype="redhat"
+      ;;
+    sles | opensuse*)
+      dtype="suse"
+      ;;
+    ubuntu | debian)
+      dtype="debian"
+      ;;
+    gentoo)
+      dtype="gentoo"
+      ;;
+    arch | manjaro)
+      dtype="arch"
+      ;;
+    slackware)
+      dtype="slackware"
+      ;;
+    *)
+      # Check ID_LIKE only if dtype is still unknown
+      if [ -n "$ID_LIKE" ]; then
+        case $ID_LIKE in
+        *fedora* | *rhel* | *centos*)
+          dtype="redhat"
+          ;;
+        *sles* | *opensuse*)
+          dtype="suse"
+          ;;
+        *ubuntu* | *debian*)
+          dtype="debian"
+          ;;
+        *gentoo*)
+          dtype="gentoo"
+          ;;
+        *arch*)
+          dtype="arch"
+          ;;
+        *slackware*)
+          dtype="slackware"
+          ;;
         esac
-    fi
+      fi
 
-    echo $dtype
+      # If ID or ID_LIKE is not recognized, keep dtype as unknown
+      ;;
+    esac
+  fi
+
+  echo $dtype
 }
-
 
 DISTRIBUTION=$(distribution)
 if [ "$DISTRIBUTION" = "redhat" ] || [ "$DISTRIBUTION" = "arch" ]; then
-      alias cat='bat'
+  alias cat='bat'
 else
-      alias cat='batcat'
-fi 
+  alias cat='batcat'
+fi
 
 # Show the current version of the operating system
 ver() {
-    local dtype
-    dtype=$(distribution)
+  local dtype
+  dtype=$(distribution)
 
-    case $dtype in
-        "redhat")
-            if [ -s /etc/redhat-release ]; then
-                cat /etc/redhat-release
-            else
-                cat /etc/issue
-            fi
-            uname -a
-            ;;
-        "suse")
-            cat /etc/SuSE-release
-            ;;
-        "debian")
-            lsb_release -a
-            ;;
-        "gentoo")
-            cat /etc/gentoo-release
-            ;;
-        "arch")
-            cat /etc/os-release
-            ;;
-        "slackware")
-            cat /etc/slackware-version
-            ;;
-        *)
-            if [ -s /etc/issue ]; then
-                cat /etc/issue
-            else
-                echo "Error: Unknown distribution"
-                exit 1
-            fi
-            ;;
-    esac
+  case $dtype in
+  "redhat")
+    if [ -s /etc/redhat-release ]; then
+      cat /etc/redhat-release
+    else
+      cat /etc/issue
+    fi
+    uname -a
+    ;;
+  "suse")
+    cat /etc/SuSE-release
+    ;;
+  "debian")
+    lsb_release -a
+    ;;
+  "gentoo")
+    cat /etc/gentoo-release
+    ;;
+  "arch")
+    cat /etc/os-release
+    ;;
+  "slackware")
+    cat /etc/slackware-version
+    ;;
+  *)
+    if [ -s /etc/issue ]; then
+      cat /etc/issue
+    else
+      echo "Error: Unknown distribution"
+      exit 1
+    fi
+    ;;
+  esac
 }
 
 # Automatically install the needed support files for this .bashrc file
 install_bashrc_support() {
-	local dtype
-	dtype=$(distribution)
+  local dtype
+  dtype=$(distribution)
 
-	case $dtype in
-		"redhat")
-			sudo yum install multitail tree zoxide trash-cli fzf bash-completion fastfetch
-			;;
-		"suse")
-			sudo zypper install multitail tree zoxide trash-cli fzf bash-completion fastfetch
-			;;
-		"debian")
-			sudo apt-get install multitail tree zoxide trash-cli fzf bash-completion
-			# Fetch the latest fastfetch release URL for linux-amd64 deb file
-			FASTFETCH_URL=$(curl -s https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest | grep "browser_download_url.*linux-amd64.deb" | cut -d '"' -f 4)
+  case $dtype in
+  "redhat")
+    sudo yum install multitail tree zoxide trash-cli fzf bash-completion fastfetch
+    ;;
+  "suse")
+    sudo zypper install multitail tree zoxide trash-cli fzf bash-completion fastfetch
+    ;;
+  "debian")
+    sudo apt-get install multitail tree zoxide trash-cli fzf bash-completion
+    # Fetch the latest fastfetch release URL for linux-amd64 deb file
+    FASTFETCH_URL=$(curl -s https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest | grep "browser_download_url.*linux-amd64.deb" | cut -d '"' -f 4)
 
-			# Download the latest fastfetch deb file
-			curl -sL $FASTFETCH_URL -o /tmp/fastfetch_latest_amd64.deb
+    # Download the latest fastfetch deb file
+    curl -sL $FASTFETCH_URL -o /tmp/fastfetch_latest_amd64.deb
 
-			# Install the downloaded deb file using apt-get
-			sudo apt-get install /tmp/fastfetch_latest_amd64.deb
-			;;
-		"arch")
-			sudo paru multitail tree zoxide trash-cli fzf bash-completion fastfetch
-			;;
-		"slackware")
-			echo "No install support for Slackware"
-			;;
-		*)
-			echo "Unknown distribution"
-			;;
-	esac
+    # Install the downloaded deb file using apt-get
+    sudo apt-get install /tmp/fastfetch_latest_amd64.deb
+    ;;
+  "arch")
+    sudo paru multitail tree zoxide trash-cli fzf bash-completion fastfetch
+    ;;
+  "slackware")
+    echo "No install support for Slackware"
+    ;;
+  *)
+    echo "Unknown distribution"
+    ;;
+  esac
 }
 
 # IP address lookup
 alias whatismyip="whatsmyip"
-function whatsmyip () {
-    # Internal IP Lookup.
-    if command -v ip &> /dev/null; then
-        echo -n "Internal IP: "
-        ip addr show wlan0 | grep "inet " | awk '{print $2}' | cut -d/ -f1
-    else
-        echo -n "Internal IP: "
-        ifconfig wlan0 | grep "inet " | awk '{print $2}'
-    fi
+function whatsmyip() {
+  # Internal IP Lookup.
+  if command -v ip &>/dev/null; then
+    echo -n "Internal IP: "
+    ip addr show wlan0 | grep "inet " | awk '{print $2}' | cut -d/ -f1
+  else
+    echo -n "Internal IP: "
+    ifconfig wlan0 | grep "inet " | awk '{print $2}'
+  fi
 
-    # External IP Lookup
-    echo -n "External IP: "
-    curl -s ifconfig.me
+  # External IP Lookup
+  echo -n "External IP: "
+  curl -s ifconfig.me
 }
 
 # Trim leading and trailing spaces (for scripts)
 trim() {
-	local var=$*
-	var="${var#"${var%%[![:space:]]*}"}" # remove leading whitespace characters
-	var="${var%"${var##*[![:space:]]}"}" # remove trailing whitespace characters
-	echo -n "$var"
+  local var=$*
+  var="${var#"${var%%[![:space:]]*}"}" # remove leading whitespace characters
+  var="${var%"${var##*[![:space:]]}"}" # remove trailing whitespace characters
+  echo -n "$var"
 }
 # GitHub Titus Additions
 
 gcom() {
-	git add .
-	git commit -m "$1"
+  git add .
+  git commit -m "$1"
 }
 lazyg() {
-	git add .
-	git commit -m "$1"
-	git push
+  git add .
+  git commit -m "$1"
+  git push
 }
 
 function hb {
-    if [ $# -eq 0 ]; then
-        echo "No file path specified."
-        return
-    elif [ ! -f "$1" ]; then
-        echo "File path does not exist."
-        return
-    fi
+  if [ $# -eq 0 ]; then
+    echo "No file path specified."
+    return
+  elif [ ! -f "$1" ]; then
+    echo "File path does not exist."
+    return
+  fi
 
-    uri="http://bin.christitus.com/documents"
-    response=$(curl -s -X POST -d @"$1" "$uri")
-    if [ $? -eq 0 ]; then
-        hasteKey=$(echo $response | jq -r '.key')
-        echo "http://bin.christitus.com/$hasteKey"
-    else
-        echo "Failed to upload the document."
-    fi
+  uri="http://bin.christitus.com/documents"
+  response=$(curl -s -X POST -d @"$1" "$uri")
+  if [ $? -eq 0 ]; then
+    hasteKey=$(echo $response | jq -r '.key')
+    echo "http://bin.christitus.com/$hasteKey"
+  else
+    echo "Failed to upload the document."
+  fi
 }
 
 #######################################################
@@ -555,12 +551,11 @@ alias hug="hugo server -F --bind=10.0.0.97 --baseURL=http://10.0.0.97"
 
 # Check if the shell is interactive
 if [[ $- == *i* ]]; then
-    # Bind Ctrl+f to insert 'zi' followed by a newline
-    bind '"\C-f":"zi\n"'
+  # Bind Ctrl+f to insert 'zi' followed by a newline
+  bind '"\C-f":"zi\n"'
 fi
 
 export PATH=$PATH:"$HOME/.local/bin:$HOME/.cargo/bin:/var/lib/flatpak/exports/bin:/.local/share/flatpak/exports/bin"
-
 
 [[ $- != *i* ]] && return
 
@@ -574,10 +569,9 @@ PS1='[\u@\h \W]\$ '
 
 # eval "$(pyenv virtualenv-init -)"
 
-
 export NVM_DIR="$HOME/.nvm"
-[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
-[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
 
 export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
@@ -595,3 +589,8 @@ export ANDROID_HOME=/home/stefantacu/Android/Sdk
 #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
 export SDKMAN_DIR="$HOME/.sdkman"
 [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
+
+# Added by Antigravity CLI installer
+export PATH="/home/stefantacu/.local/bin:$PATH"
+. "/home/stefantacu/.deno/env"
+source /home/stefantacu/.local/share/bash-completion/completions/deno.bash
